### TRAINING SEED (MANUAL LABELED) DATA

In [ ]:
!pip install -U scikit-learn transformers torch sastrawi tqdm matplotlib

In [4]:
import pandas as pd

TRAIN_DATA_PATH = '../../data/data_berita/train_data/'

In [8]:
df1 = pd.read_csv(f"{TRAIN_DATA_PATH}/cnbc_train_data.csv")
df2 = pd.read_csv(f"{TRAIN_DATA_PATH}/detik_train_data.csv")
df3 = pd.read_csv(f"{TRAIN_DATA_PATH}/kompas_train_data.csv")

print(df1.columns)
display(df1.head())
print(df2.columns)
display(df2.head())
print(df3.columns)
display(df3.head())

Index(['date', 'title', 'content', 'article_id', 'text', 'label'], dtype='object')

,date,title,content,article_id,text,label
0,2019-09-11,menko luhut jokowi tak mungkin asal pilih ment...,"jakarta, cnbc indonesia- presiden joko widodo ...",CNBC_00008,menko luhut jokowi tak mungkin asal pilih ment...,0
1,2019-09-24,ini siasat lobi-lobi boris saat brexit makin u...,"jakarta, cnbc indonesia-kurang dari 40 hari je...",CNBC_00012,ini siasat lobi-lobi boris saat brexit makin u...,0
2,2019-10-06,"menterinya terbanyak se-asean, kabinet ri baka...","cnbc indonesia, jakarta -jelang pelantikan kab...",CNBC_00017,"menterinya terbanyak se-asean, kabinet ri baka...",0
3,2019-10-16,akankah gerindra masuk koalisi jokowi?,"jakarta, cnbc indonesia -partai gerindra mengg...",CNBC_00023,akankah gerindra masuk koalisi jokowi?. jakart...,0
4,2019-10-16,"kubu prabowo masuk koalisi jokowi, berkah atau...","berbicara mengenai perekonomian, investasi men...",CNBC_00026,"kubu prabowo masuk koalisi jokowi, berkah atau...",1

Index(['date', 'title', 'content', 'text', 'label', 'article_id'], dtype='object')

,date,title,content,text,label,article_id
0,2023-12-20,mendagri copot pj bupati kampar karena tak net...,menteri dalam negeri mendagri tito karnavian m...,mendagri copot pj bupati kampar karena tak net...,-1,DETIK_7302
1,2025-06-20,waka mpr nilai keputusan prabowo absen di g7 j...,"wakil ketua mpr dari fraksi pan, eddy soeparno...",waka mpr nilai keputusan prabowo absen di g7 j...,0,DETIK_1543
2,2024-02-14,"setelah nyoblos, ahy bakal merapat ke istora s...",tim kampanye nasional tkn prabowo-gibran bakal...,"setelah nyoblos, ahy bakal merapat ke istora s...",0,DETIK_6055
3,2024-06-05,obrolan jk dan baradar jika diizinkan saya ban...,wakil perdana menteri 1 afghanistan mullah abd...,obrolan jk dan baradar jika diizinkan saya ban...,0,DETIK_4993
4,2023-10-31,golkar masih lobi khofifah gabung tkn prabowo-...,sekjen partai golkar lodewijk f paulus berbica...,golkar masih lobi khofifah gabung tkn prabowo-...,0,DETIK_8269

Index(['date', 'title', 'content', 'label', 'article_id', 'text'], dtype='object')

,date,title,content,label,article_id,text
0,2022-01-23,polemik arteria dahlan jadi pembelajaran kader...,sekretaris jenderal pdi-p hasto kristiyanto m...,0,KOMPAS_9963,polemik arteria dahlan jadi pembelajaran kader...
1,2022-01-23,"hut ke-75 megawati, pramono anung politik ibu ...",mantan sekretaris jenderal pdi perjuangan pra...,0,KOMPAS_9962,"hut ke-75 megawati, pramono anung politik ibu ..."
2,2022-01-24,pengamat tebak pesan anies ke giring kalau sum...,direktur eksekutif parameter politik indonesi...,0,KOMPAS_9956,pengamat tebak pesan anies ke giring kalau sum...
3,2022-01-24,update 20.867 kasus aktif covid-19 di indonesia,pemerintah menyampaikan terdapat 20.867 kasus...,-1,KOMPAS_9945,update 20.867 kasus aktif covid-19 di indonesi...
4,2022-01-25,update 25 januari 7.483 kasus suspek covid-19 ...,"pemerintah mencatat, hingga selasa 25 1 2022 ...",-1,KOMPAS_9936,update 25 januari 7.483 kasus suspek covid-19 ...

In [1]:
# =========================
# Core
# =========================
import os
import re
import math
import random
from dataclasses import dataclass
from typing import List, Dict, Optional, Tuple

# =========================
# Data / Numeric
# =========================
import numpy as np
import pandas as pd

# =========================
# Visualization (optional)
# =========================
import matplotlib.pyplot as plt

# =========================
# Sklearn (split + metrics)
# =========================
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    f1_score,
    precision_recall_fscore_support
)

# =========================
# PyTorch
# =========================
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

# =========================
# Hugging Face Transformers (IndoBERT)
# =========================
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    DataCollatorWithPadding,
    TrainingArguments,
    Trainer,
    set_seed
)

# =========================
# (Optional) Sastrawi
# =========================
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

# =========================
# (Optional) Progress bar
# =========================
from tqdm.auto import tqdm

ModuleNotFoundError: No module named 'sklearn'